
import { Translation } from './types';

export const TRANSLATIONS: Translation = {
  login: { en: 'Login', ta: 'உள்நுழை' },
  username: { en: 'Username', ta: 'பயனர் பெயர்' },
  password: { en: 'Password', ta: 'கடவுச்சொல்' },
  admin: { en: 'Admin', ta: 'நிர்வாகி' },
  basic: { en: 'Basic', ta: 'அடிப்படை' },
  forgotPassword: { en: 'Forgot Password?', ta: 'கடவுச்சொல் மறந்துவிட்டதா?' },
  register: { en: 'Register', ta: 'பதிவு செய்க' },
  dashboard: { en: 'Dashboard', ta: 'டாஷ்போர்டு' },
  khss: { en: 'Kolli Hills Savings Scheme', ta: 'கொல்லி மலை சேமிப்பு திட்டம்' },
  dss: { en: 'Diwali Savings Scheme', ta: 'தீபாவளி சேமிப்பு திட்டம்' },
  finance: { en: 'Finance', ta: 'நிதி' },
  addUser: { en: 'Add User', ta: 'பயனரைச் சேர்' },
  addLoginUser: { en: 'Add Login User', ta: 'உள்நுழைவு பயனரைச் சேர்' },
  userDetails: { en: 'User Details', ta: 'பயனர் விவரங்கள்' },
  schemeSettings: { en: 'Scheme Settings', ta: 'திட்ட அமைப்புகள்' },
  logout: { en: 'Logout', ta: 'வெளியேறு' },
  name: { en: 'Name', ta: 'பெயர்' },
  phone: { en: 'Phone Number', ta: 'தொலைபேசி எண்' },
  email: { en: 'Email ID', ta: 'மின்னஞ்சல் முகவரி' },
  address: { en: 'Address', ta: 'முகவரி' },
  userType: { en: 'User Type', ta: 'பயனர் வகை' },
  submit: { en: 'Submit', ta: 'சமர்ப்பி' },
  save: { en: 'Save', ta: 'சேமி' },
  cancel: { en: 'Cancel', ta: 'ரத்து செய்' },
  search: { en: 'Search', ta: 'தேடு' },
  customerId: { en: 'Customer ID', ta: 'வாடிக்கையாளர் ஐடி' },
  totalAmount: { en: 'Total Amount', ta: 'மொத்த தொகை' },
  paidAmount: { en: 'Paid Amount', ta: 'செலுத்திய தொகை' },
  balance: { en: 'Balance', ta: 'இருப்பு' },
  paymentAmount: { en: 'Payment Amount', ta: 'பணம் செலுத்தும் தொகை' },
  back: { en: 'Back', ta: 'பின்செல்' },
  itemSelection: { en: 'Item Selection', ta: 'பொருளைத் தேர்ந்தெடுக்கவும்' },
  numSchemes: { en: 'Number of Schemes', ta: 'திட்டங்களின் எண்ணிக்கை' },
  copperKudam: { en: 'Copper Kudam', ta: 'செப்பு குடம்' },
  kuthuVizhakku: { en: 'Kuthu Vizhakku', ta: 'குத்து விளக்கு' },
  deleteConfirm: { en: 'Are you sure you want to delete?', ta: 'நிச்சயமாக நீக்க வேண்டுமா?' },
  noUsersFound: { en: 'No users found.', ta: 'பயனர்கள் யாரும் இல்லை.' },
  success: { en: 'Success!', ta: 'வெற்றி!' },
  error: { en: 'Error!', ta: 'பிழை!' },
  invalidPhone: { en: 'Mobile number must be exactly 10 digits.', ta: 'தொலைபேசி எண் 10 இலக்கங்களாக இருக்க வேண்டும்.' },
};

export const INITIAL_ADMIN = {
  username: 'Test',
  password: 'Test@123',
};
